const A=require('node:assert/strict'),fs=require('node:fs'),V=require('../src/scoring-v3.cjs'),V2=require('../src/scoring-v2.cjs');
let n=0;const test=(s,f)=>{f();n++;console.log('PASS '+s);},near=(x,y)=>A.ok(Math.abs(x-y)<1e-10);
const ex=require('../examples/v3_domestic20.json'),a=ex.answers;
test('20대 여의도 최대 잠정 가산',()=>near(V.placeAgeBonus('kdx24',a).score,.015));
test('20대 에버랜드 관측비율',()=>near(V.placeAgeBonus('nax288',a).score,.015*6.7/9.3));
test('10대 가산 없음',()=>near(V.placeAgeBonus('kdx24',{...a,0:0}).score,0));
test('해외 모드 가산 없음',()=>near(V.placeAgeBonus('kdx24',{...a,5:1}).score,0));
test('연령 미응답 없음',()=>near(V.placeAgeBonus('kdx24',{5:0}).score,0));
test('60대와 70대 통합 구간',()=>near(V.placeAgeBonus('ro17',{...a,0:5}).score,V.placeAgeBonus('ro17',{...a,0:6}).score));
test('미관측 장소 가산 없음',()=>near(V.placeAgeBonus('unknown',a).score,0));
test('특정 연령 Top30 밖 가산 없음',()=>near(V.placeAgeBonus('kdx24',{...a,0:5}).score,0));
test('검증 모드 잠정 연결 제외',()=>near(V.placeAgeBonus('kdx24',a,{strictVerified:true}).score,0));
test('동명이소 보문사 보류',()=>near(V.placeAgeBonus('ro38',a).score,0));
test('미매핑 슬롯 분모 유지',()=>near(V.candidateAgeBonus({parseSupported:true,slots:[{placeId:'kdx24',linkWeight:1},{placeId:null,linkWeight:0}]},a).score,.0075));
test('경로 잠정 연결 추가 감쇠',()=>near(V.candidateAgeBonus({parseSupported:true,slots:[{placeId:'kdx24',linkWeight:.5}]},a).score,.0075));
test('미지원 경로 0',()=>near(V.candidateAgeBonus({parseSupported:false,slots:[]},a).score,0));
test('계수 상한',()=>A.throws(()=>V.placeAgeBonus('kdx24',a,{beta:1})));
test('기존 장소점수 추가',()=>near(V.applyAgeToPlace({placeId:'kdx24',score:.7},a).score,.715));
const old=V2.recommendV2(ex),r=V.recommendV3(ex);
test('유형 점수 유지',()=>A.deepEqual(r.legacy.trace.totalScores,old.legacy.trace.totalScores));
test('전 테마 지역 연령예산 상한',()=>r.allThemes.forEach(t=>A.ok(t.age.regionalTermAfter<=.05000001&&t.age.regionalTermAfter>=-.05000001)));
test('전 코스 가산 상한',()=>r.allCities.forEach(t=>A.ok(t.age.score>=0&&t.age.score<=.00750001)));
test('실제 코스 일부 가산',()=>A.ok(r.allCities.some(t=>t.age.score>0)));
test('정렬 뒤 지역 대표',()=>A.deepEqual(r.cityPicks,V2.pickDistinctRegions(r.allCities)));
test('strict는 전 테마 및 코스 기존점수',()=>{let z=V.recommendV3({...ex,ageOptions:{strictVerified:true}});z.allThemes.forEach(t=>near(t.score,t.scoreBeforeAge));z.allCities.forEach(t=>near(t.score,t.scoreBeforeAge));});
test('교체 코스에 기본 인덱스 프로필 미적용',()=>{let row=[...r.allCities[0].raw];row[1]='CUSTOM';let z=V.recommendV3({...ex,tours:[row]});near(z.allCities[0].age.score,0);});
fs.writeFileSync('examples/v3_verification.json',JSON.stringify({passed:n,failed:0,ageEffectCities:r.allCities.filter(x=>x.age.score>0).length,scope:'provisional mapping; not deployed'},null,2));
console.log(n+' new age tests passed');
