const A=require('node:assert/strict'),fs=require('node:fs'),V=require('../src/scoring-v4.cjs'),V3=require('../src/scoring-v3.cjs'),V2=require('../src/scoring-v2.cjs'),D=require('../data/region-demographics.json');
let n=0;const test=(s,f)=>{f();n++;console.log('PASS '+s);},near=(x,y)=>A.ok(Math.abs(x-y)<1e-10,`${x} != ${y}`),ex=require('../examples/v4_domestic30female.json'),a=ex.answers;
test('독립된 주변비율90지역만 적재',()=>A.equal(Object.keys(D.regions).length,90));
test('충돌4지역 제외',()=>A.ok(!Object.keys(D.regions).some(x=>/제물포구|영종구|서해구|검단구/.test(x))));
test('기준값은 선택자료 중앙값',()=>near(D.benchmarkSex.male,.6106));
test('중앙값이면 가산0',()=>near(V.relativeEvidence(.2,.2),0));
test('기준2배면 증거상한1',()=>near(V.relativeEvidence(.4,.2),1));
test('기준미만 감점 안함',()=>near(V.relativeEvidence(.1,.2),0));
test('0구성비 안전처리',()=>near(V.relativeEvidence(0,.2),0));
test('잘못된 기준값 오류',()=>A.throws(()=>V.relativeEvidence(.1,0)));
test('10대 지역지표 지원',()=>A.equal(V.regionAgeBand({...a,0:0}),'10대'));
test('60대 세분 지원',()=>A.equal(V.regionAgeBand({...a,0:5}),'60대'));
test('70대 이상 경계 미확인으로 연령항 보류',()=>A.equal(V.regionAgeBand({...a,0:6}),null));
test('남성거제 실제가산 분해',()=>{let r=V.regionalBonus('거제',a,{sex:'male'});near(r.score,r.agePart+r.sexPart);near(r.sexPart,.02*.5*.25*Math.log2(.6108/.6106));});
test('성별 미입력 가중치 재분배 없음',()=>{let r=V.regionalBonus('거제',a,{});near(r.sexPart,0);near(r.score,.02*.5*.75*r.ageEvidence);});
test('해외 제외',()=>near(V.regionalBonus('거제',{...a,5:1},{sex:'male'}).score,0));
test('기능끄기',()=>near(V.regionalBonus('거제',a,{enabled:false,sex:'male'}).score,0));
test('검증모드 제외',()=>near(V.regionalBonus('거제',a,{sex:'male'},{strictVerified:true}).score,0));
test('광역부산 집계금지',()=>near(V.regionalBonus('부산',a,{sex:'male'}).score,0));
test('동명이소고성 보류',()=>near(V.regionalBonus('고성',a,{sex:'male'}).score,0));
test('성별 입력오류',()=>A.throws(()=>V.regionalBonus('거제',a,{sex:'X'})));
test('enabled 입력오류',()=>A.throws(()=>V.regionalBonus('거제',a,{enabled:'false'})));
test('교차분포 사용 없음',()=>A.equal(V.regionalBonus('거제',a,{sex:'female'}).jointSexAgeUsed,false));
const r=V.recommendV4(ex),old=V3.recommendV3(ex);
test('유형점수 불변',()=>A.deepEqual(r.legacy.trace.totalScores,old.legacy.trace.totalScores));
test('한류 선호 불변',()=>A.deepEqual(r.preference,old.preference));
test('지역보정끄면v3점수 일치',()=>{let q=V.recommendV4({...ex,demographics:{enabled:false}});q.allThemes.forEach(t=>near(t.score,old.allThemes.find(o=>o.k===t.k).score));q.allCities.forEach(t=>near(t.score,old.allCities.find(o=>o.index===t.index).score));});
test('테마 공통보정상한',()=>r.allThemes.forEach(t=>A.ok(t.regionalDemographics.regionalTermAfter<=.05000001)));
test('코스 인구통계 가산상한',()=>r.allCities.forEach(t=>A.ok(t.regionalDemographics.combinedDemographicBonus<=.02000001)));
test('전체정렬 후 지역대표',()=>A.deepEqual(r.cityPicks,V2.pickDistinctRegions(r.allCities)));
test('지역별대표 중복없음',()=>A.equal(new Set(r.cityPicks.map(t=>t.region)).size,r.cityPicks.length));
test('장소 전체상한',()=>{for(let id of Object.keys(D.placeRegion)){let p=V.applyDemographicsToPlace({placeId:id,score:.3},a,{sex:'female'});A.ok(p.score>=.3&&p.score<=.320000001);}});
test('strict는v2까지두보정제외',()=>{let q=V.recommendV4({...ex,ageOptions:{strictVerified:true}});q.allThemes.forEach(t=>near(t.score,t.scoreBeforeAge));q.allCities.forEach(t=>near(t.score,t.scoreBeforeAge));});
fs.writeFileSync('examples/v4_verification.json',JSON.stringify({passed:n,failed:0,cityCoursesNewBonus:r.allCities.filter(x=>x.regionalDemographics.score>0).length,version:r.version,deployed:false},null,2));console.log(n+' new regional demographic tests passed');
